GoogleForms/GoogleForms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forms.urls'))
]

GoogleForms/forms/urls.py
from django.urls import path
from . import views

app_name = 'forms'

urlpatterns = [
    path('', views.home,name = 'home',),
    path('create/', views.create, name='create'),
    path('forms/<str:pk>/edit', views.update_form, name='update_form'),
    path('response/<str:pk>/viewForm', views.get_response_from_user, name='view_form'),
    path('forms/<str:pk>/responses', views.responses, name='responses'),
]

GoogleForms/forms/models.py
from django.db import models

# Create your models here.

GoogleForms/forms/admin.py
from django.contrib import admin

# Register your models here.

GoogleForms/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'forms'

GoogleForms/forms/tests.py
from django.test import TestCase

# Create your tests here.

GoogleForms/forms/utils.py
import pymongo
from django.utils import timezone

from bson import ObjectId

client = pymongo.MongoClient('mongodb://localhost:27017/')
db = client['GoogleForms']
col = db['GoogleForms']

class Form:
    def create(self):
        obj = col.insert_one({
            'created':timezone.now()
        })
        return str(obj.inserted_id)

    def find(self, pk):
        query = {
            '_id':ObjectId(pk)
        }
        obj = col.find(query).next() # cursor

        return obj

    def update(self, pk, form_data):
        query = {'_id':ObjectId(pk)}
        updated_value = {
            '$set':{
                'form_data':form_data['formData'],
                'updated': timezone.now()
            }
        }

        col.update_one(query, updated_value)
        print('form_updated')

    def findall(self):
        return col.find().sort('updated', -1)

    def update_response(self, pk, response):
        query = {'_id':ObjectId(pk)}
        updated_value = {
            '$inc':response
        }
        col.update_one(query, updated_value)

GoogleForms/forms/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse_lazy
from django.http import Http404, JsonResponse
from .utils import Form
import json

# Create your views here.

form = Form()

def get_random_uuid():
    return 'my_simple_uuid'

def home(request):
    forms = form.findall()
    return render(request, 'home.html', {
        'forms':forms
    })

def create(request):
    pk = form.create()
    return HttpResponseRedirect(reverse_lazy('forms:update_form', args=[pk]))

def update_form(request, pk):

    if request.method == 'POST':
        form_data = json.loads(request.body)
        form.update(pk, form_data)
        return JsonResponse({
            'saved':'OK'
        })
        print(data)

    try:
        form_data = form.find(pk)
        return render(request, 'update_form.html', {
            'pk':pk,
            'form':form_data
        })
    except Exception as e:
        print(e)
        raise Http404('Form not found')

def get_response_from_user(request, pk):
    if request.method == 'POST':
        cd = dict(request.POST)
        del cd['csrfmiddlewaretoken']
        response = {}
        for key, value in cd.items():
            print(key, value[0])
            response.update({
                f"responses.{key}.{value[0]}":1
            })
        form.update_response(pk, response)
        return render(request, 'thankyou.html')
    else:
        try:
            form_data = form.find(pk)
            return render(request, "get_response_from_user.html",{
                'pk':pk,
                'form_data':form_data
            })
        except:
            raise Http404('Form not found')

def responses(request, pk):
    form_data = form.find(pk)
    return render(request, 'responses.html', {
        'form_data':form_data
    })

GoogleForms/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body>
    {% block content %}{% endblock content %}
</body>

{% block script %}{% endblock script %}

</html>

GoogleForms/templates/get_response_from_user.html
{% extends 'base.html' %}

{% block content %}

<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{form_data.form_data.title}}</h5>
        <p class="card-text">{{form_data.form_data.description}}</p>
    </div>
</div>


<form action="{% url 'forms:view_form' pk %}" method='POST'>
    {% csrf_token %}

    {% with form_data.form_data.data as questions %}
        {% for questionID, questionData in questions.items %}
            <div class="card mt-2">
                <div class="card-header fw-bold">
                    Question {{forloop.counter}}
                </div> 
                <div class='card-body'>
                    <div class="form-floating mb-2">
                        <p id="{{questionID}}" class='font-monospace fs-5'>{{questionData.questionText}}</p>
                    </div>                    
                </div>
                {% for option in questionData.options %}
                <div class="form-check">
                    <input class="form-check-input" type="radio" id="{{questionID}}-{{forloop.counter}}" name="{{questionID}}" value={{option}}>
                    <label class="form-check-label" for="{{questionID}}-{{forloop.counter}}">
                        {{option}}
                    </label>
                </div>
                {% endfor %}                
            </div>
        
        {% endfor %}
    {% endwith %}

<input type="Submit" value="Submit" class='mt-2'>
</form>


{% endblock content %}

GoogleForms/templates/home.html
{% load form_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>

    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td,
        th {
            text-align: left;
            padding: 8px;
        }
    </style>

</head>
<body>
    <h1>FormsBase</h1>
    <a href="{% url 'forms:create' %}"><button>Create Form</button></a>

    <table>
        <tr>
            <th>Title</th>
            <th>Updated On</th>
            <th>Created On</th>
            <th>View</th>
        </tr>
    

    {% for form in forms %}
    {% if form.updated %}
        <tr>
            <td>{{form.form_data.title}}</td>
            <td>{{form.updated}}</td>
            <td>{{form.created}}</td>
            <td><a href="{% url 'forms:update_form' form|lookup:"_id" %}" target="_blank">Open in new tab</a></td>
        </tr>

    {% endif %}
    {% endfor %}

    </table>
</body>
</html>

GoogleForms/templates/responses.html
{% extends 'base.html' %}
{% load form_filters %}

{% block content %}
    <h1>Responses</h1>
    {% with form_data.form_data as form %}
        {% with form.data as data %}
            {% for questionID, responses in form_data.responses.items %}

                <div class="card">
                    <div class="card-header font-monospace fw-bold">
                        {% with data|lookup:questionID as question %} Q{{forloop.counter}}. {{question.questionText}} {% endwith %}
                    </div>
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">Option</th>
                                    <th scope="col">Response</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for response, count in responses.items %}
                                <tr>
                                    <td>{{response}}</td>
                                    <td>{{count}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

                

            {% endfor %}
        {% endwith %}
    {% endwith %}
{% endblock content %}

GoogleForms/templates/thankyou.html
{% extends 'base.html' %}

{% block content %}Thank you. Your response is saved.{% endblock content %}

GoogleForms/templates/update_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>Update Form</h1>

<a href="{% url 'forms:view_form' pk %}" target="_blank"><button>Share</button></a>
<a href="{% url 'forms:responses' pk %}"><button>Responses</button></a>
    
<form action="{% url 'forms:update_form' pk %}" method="post" id='questionForm'>
    {% csrf_token %}
    <Button type='submit'>Save</Button>

    <div class="card" id='form-description'>
        <div class="card-header">
            Title and Description
        </div>
        <div class="card-body">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="title" placeholder="title" name='title'>
                <label for="title">Form Title</label>
            </div>
            <div class="form-floating">
                <textarea class="form-control" placeholder="Description" id="description"
                    name='description'></textarea>
                <label for="description">Form Description</label>
            </div>
        </div>
        <button type='button' id='addQuestion'>Add Question</button>
    </div>


{% endblock content %}

{% block script %}
    <script src="{% static 'forms.js' %}"></script>

    <script>
    
        let children = form.children
        children[2].querySelector('[name=title]').value = "{{form.form_data.title|escapejs}}"
        children[2].querySelector('[name=description]').value = "{{form.form_data.description|escapejs}}"


        {% if form.form_data.data %}
        
            let addQuestionButtonId = 'addQuestion';
            let addOptionButtonId, question,option_id;
            let i=0;

            {% with form.form_data.data as questions %}

                {% for questionId, questionData in questions.items %}
                
                    i = {{forloop.counter0|escapejs}}+3;
                    [addQuestionButtonId, addOptionButtonId] = addQuestion(addQuestionButtonId, false);

                    children[i].querySelector('.question').value = "{{questionData.questionText|escapejs}}";

                    {% for option in questionData.options %}
                    
                        option_id = addOption(addOptionButtonId);
                        all_opt = children[i].querySelector('.allOptions').children;
                        all_opt[all_opt.length-1].querySelector(`#${option_id}`).value = '{{option}}';

                    {% endfor %}

                {% endfor %}
            
            {% endwith %}

        {% endif %}


    </script>

{% endblock script %}